# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param a the first parameter of Gibbs sampler proposition distribution of rbeta of y
#' @param b the second parameter of Gibbs sampler proposition distribution of rbeta of y
#' @param n the parameter of Gibbs sampler proposition distribution of rbinom of x
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' rnC <- GibbsC(1e3,10,2,3,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
GibbsC <- function(N, thin, a, b, n) {
    .Call('_SA23204162_GibbsC', PACKAGE = 'SA23204162', N, thin, a, b, n)
}

